controlplane:
  hosts:
    k8s-m1:
      ansible_host: 172.16.4.205

master:
  hosts:
    k8s-m2:
      ansible_host: 172.16.4.53
    k8s-m3:
      ansible_host: 172.16.3.80

k8s:
  children:
    controlplane:
    master:
  vars:
    ansible_port: 22
    ansible_user: k8s

all:
  children:
    k8s: