all:
  children:
    k8s:
      children:
        controlplane:
          hosts:
            k8s-m1:
              ansible_host: 172.16.4.205
              ansible_port: 22
              ansible_user: k8s
        master:
          hosts:
            k8s-m2:
              ansible_host: 172.16.4.53
              ansible_port: 22
              ansible_user: k8s
            k8s-m3:
              ansible_host: 172.16.3.80
              ansible_port: 22
              ansible_user: k8s